
국가(도시 하나)별 판매량등
regions
conutries
locations
wherehouse
inventories
product_categories
products
order_items
orders

SELECT c.COUNTRY_NAME, l.CITY, SUM(oi.QUANTITY * oi.UNIT_PRICE) total
FROM ORDERS o 
JOIN ORDER_ITEMS oi
	ON o.ORDER_ID = oi.ORDER_ID 
JOIN PRODUCTS p 
	ON oi.PRODUCT_ID = p.PRODUCT_ID 
JOIN INVENTORIES i 
	ON p.PRODUCT_ID = i.PRODUCT_ID 
JOIN WAREHOUSES w 
	ON i.WAREHOUSE_ID = w.WAREHOUSE_ID 
JOIN LOCATIONS l 
	ON w.LOCATION_ID = l.LOCATION_ID 
JOIN COUNTRIES c 
	ON l.COUNTRY_ID = c.COUNTRY_ID 
JOIN REGIONS r 
	ON c.REGION_ID = r.REGION_ID 
GROUP BY c.COUNTRY_NAME, l.CITY
ORDER BY total desc


지역별 어떤제품이 몇개 팔렸다
locations
wherehouse
inventories
product_categories
products
order_items
ORDER

상품별 얼마나 팔렸는지
products
order_items
orders
상품별 총매출
SELECT p.PRODUCT_NAME, SUM(oi.QUANTITY * oi.UNIT_PRICE) AS TOTAL
FROM ORDERS o 
JOIN ORDER_ITEMS oi 
	ON o.ORDER_ID = oi.ORDER_ID 
JOIN PRODUCTS p 
	ON oi.PRODUCT_ID = p.PRODUCT_ID 
GROUP BY p.PRODUCT_NAME


직원별 매출
employees
orders
order_items

SELECT (e.FIRST_NAME || ' ' || e.LAST_NAME) EMPLOYEES_NAME, SUM(oi.QUANTITY * oi.UNIT_PRICE) sum, avg(oi.QUANTITY * oi.UNIT_PRICE) avg, max(oi.QUANTITY * oi.UNIT_PRICE) max, min(oi.QUANTITY * oi.UNIT_PRICE) min, COUNT(oi.QUANTITY * oi.UNIT_PRICE) COUNT, stddev(oi.QUANTITY * oi.UNIT_PRICE) stddev 
FROM EMPLOYEES e 
JOIN ORDERS o 
	ON e.EMPLOYEE_ID = o.SALESMAN_ID 
JOIN ORDER_ITEMS oi 
	ON o.ORDER_ID = oi.ORDER_ID 
GROUP BY (e.FIRST_NAME || ' ' || e.LAST_NAME)


매니저가 몇명의 직원을 관리하는지
SELECT (m.FIRST_NAME || ' ' || m.LAST_NAME) MANAGER_NAME, count(e.FIRST_NAME || ' ' || e.LAST_NAME) EMPLOYEES_COUNT
FROM EMPLOYEES e
INNER JOIN EMPLOYEES m 
	ON e.MANAGER_ID = m.EMPLOYEE_ID
GROUP BY (m.FIRST_NAME || ' ' || m.LAST_NAME)
ORDER BY EMPLOYEES_COUNT DESC


직원별 어떤상품을 많이 팔았는지
employees
orders
order_items
products
WITH RANK_T as(
SELECT (e.FIRST_NAME || ' ' || e.LAST_NAME) EMPLOYEES_NAME, ROW_NUMBER() OVER (PARTITION BY oi.PRODUCT_ID ORDER BY oi.QUANTITY) AS SALE_RANK, pc.CATEGORY_NAME AS CATEGORY, p.PRODUCT_NAME AS PRODUCT_NAME
FROM EMPLOYEES e 
JOIN ORDERS o 
	ON e.EMPLOYEE_ID = o.SALESMAN_ID 
JOIN ORDER_ITEMS oi 
	ON o.ORDER_ID = oi.ORDER_ID 
JOIN PRODUCTS p 
	ON oi.PRODUCT_ID = p.PRODUCT_ID 
JOIN PRODUCT_CATEGORIES pc 
	ON p.CATEGORY_ID = pc.CATEGORY_ID 
)
SELECT EMPLOYEES_NAME, CATEGORY, PRODUCT_NAME, SALE_RANK
FROM RANK_T
WHERE SALE_RANK = 1



직원별 어떤 종류를 많이 팔았는지



어떤 고객이 많은 금액을 지불했는지*
contacts
customers
orders
order_items
고객별 총 매출
SELECT (c.FIRST_NAME || ' ' || c.LAST_NAME) AS CUSTOMER_NAME, sum(oi.QUANTITY * oi.UNIT_PRICE) TOTAL_SALES
FROM CONTACTS c 
JOIN CUSTOMERS c2 
	ON c.CUSTOMER_ID = c2.CUSTOMER_ID 
JOIN ORDERS o 
	ON c2.CUSTOMER_ID = o.CUSTOMER_ID 
JOIN ORDER_ITEMS oi 
	ON o.ORDER_ID  = oi.ORDER_ID 
GROUP BY c.FIRST_NAME, c.LAST_NAME
ORDER BY TOTAL_SALES DESC 




고객별 기간별 총매출
SELECT (c.FIRST_NAME || ' ' || c.LAST_NAME) AS CUSTOMER_NAME, o.ORDER_DATE AS order_date, sum(oi.QUANTITY * oi.UNIT_PRICE) TOTAL_SALES
FROM CONTACTS c 
JOIN CUSTOMERS c2 
	ON c.CUSTOMER_ID = c2.CUSTOMER_ID 
JOIN ORDERS o 
	ON c2.CUSTOMER_ID = o.CUSTOMER_ID 
JOIN ORDER_ITEMS oi 
	ON o.ORDER_ID  = oi.ORDER_ID 
GROUP BY c.FIRST_NAME, c.LAST_NAME, o.ORDER_DATE
ORDER BY TOTAL_SALES DESC 



